name: Daily Check for update

on:
  schedule:
    - cron:  '0 0 */1 * *'

env:
  ZXINC_CHECK_URL: 'https://www.zxinc.org/update.php?app=ipv6db&type=json'
  ZXINC_IP_7Z:  'http://ip.zxinc.org/ip.7z'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependence
      run: sudo apt-get install p7zip-full jq
    
    - name: Get last version
      id: last-history
      run: |
        max_history_version=0
        for i in $(ls '${{ github.workspace }}/history'); do
            test_version=$((${i} + 0))
            [[ ${test_version} -gt ${max_history_version} ]] && max_history_version=${test_version}
        done
        echo "::set-output name=last::$(max_history_version)"
    
    - name: Get current version
      id: current-history
      run: |
        echo "::set-output name=current::$(($(curl -L ${{ env.ZXINC_CHECK_URL }} | jq -r '.newver' ) + 0))"

    - name: Unpack New version
      id: unpack-new
      if: ${{ steps.current-history.outputs.current }} -gt ${{ steps.last-history.outputs.last }}
      run: |
        wget ${{ env.ZXINC_IP_7Z }} -P ${{ runner.temp }}
        7z x "${{ runner.temp }}/ip.7z" -y -o"${{ runner.temp }}/ipv6_${{ steps.current-history.outputs.now }}"

        mkdir "${{ github.workspace }}/history/${{ steps.current-history.outputs.now }}"
        cp ${{ runner.temp }}/ipv6_${{ steps.current-history.outputs.now }}/*.db "${{ github.workspace }}/history/${{ steps.current-history.outputs.now }}"
        rm ${{ github.workspace }}/*.db  # 移除当前目录下的`ipv6wry.db`
        cp ${{ runner.temp }}/ipv6_${{ steps.current-history.outputs.now }}/*.db '${{ github.workspace }}'

        db_count=$(cat "${{ runner.temp }}/ipv6_${{ steps.current-history.outputs.now }}/说明.txt" | grep -E -o "IP数据记录：[0-9]*" | grep -E -o "[0-9]*")
        db_size=$(cat "${{ runner.temp }}/ipv6_${{ steps.current-history.outputs.now }}/说明.txt" | grep -E -o "数据库大小：.*MiB" | sed "s/数据库大小：//g")

        sed -i "s/当前版本: \`[0-9]\{8\}\`/当前版本: \`${{ steps.current-history.outputs.now }}\`/g"  README.md
        sed -i "s/<\!-- update info here -->/| ${{ steps.current-history.outputs.now }} \| ${db_count} \| ${db_size} \| \n<\!-- update info here -->/" README.md

        rm -rf "${{ runner.temp }}/ipv6_${{ steps.current-history.outputs.now }}"
        rm "${{ runner.temp }}/ip.7z"
    
    - name: Commit files
      if: ${{ steps.current-history.outputs.current }} -gt ${{ steps.last-history.outputs.last }}
      run: |
        DATE=`date +%Y-%m-%d`
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -a -m ":arrow_up: Daily update at $DATE"

    - name: Push changes
      uses: ad-m/github-push-action@master
      if: ${{ steps.current-history.outputs.current }} -gt ${{ steps.last-history.outputs.last }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  
